### ISSUE TITLE
Only first zone detected?

### ISSUE THREAD

**Issue by andrew-burgher** [bstillitano/homebridge-actron-neo#1]
My system has multiple (n=7) zones. Appears that only the first zone has been detected and registered as an accessory.

Homebridge Version: 1.6.1
Plugin Version: 1.2.13

**Comment by ruaandeysel** [comment]
@bstillitano Same with my system. 

I have 5 zone sensors and only 1 zone has been detected / registered. 

I noticed it detected outdoor unit and registered as sensor. 

Please let me know if I need to send you any log files.

**Comment by bstillitano** [comment]
Ok, version `0.0.16` fixes this. You can now set zones on/off. Will be making improvements to the duplicate zones over time. For now though, closing out this issue.

**Comment by bstillitano** [comment]
Please not also @ruaandeysel @andrew-burgher you'll need to remove `@bstillitano/homebridge-actron-neo` and install `homebridge-actron-neo` to get the newer versions.

I know this is annoying but was a requirement as part of the Homebridge verification process.

**Comment by ruaandeysel** [comment]
Thank you very much for all the work you are putting into this plugin @bstillitano

**Comment by ruaandeysel** [comment]
@bstillitano not sure if this will be of any future help. Here's code repo for ActronAir Que/Neo Home assistant add-on 

https://github.com/MikeJMcGuire/HASSAddons/tree/master/hass-actronque/hass-actronque
