### ISSUE TITLE
HTTP 503 when enabling a zone

### ISSUE THREAD

**Issue by andrew-burgher** [bstillitano/homebridge-actron-neo#3]
Unable to control a zone

1. Turn off zone on Master Controller
2. Select 'Heat' option for zone accessory in Home app
3. Observe errors in HB log:
[Actron Neo] Maximum retries exceeded -> Actron Neo API returned a server side error: http status code = 504
[Actron Neo] API Error when attempting command send:
 {"command":{"UserAirconSettings.EnabledZones[0]":true,"type":"set-settings"}}
[Actron Neo] Failed to send command, Actron Neo Cloud unreachable

Homebridge Version: 1.6.1
Plugin Version: 1.2.13

**Comment by bstillitano** [comment]
Resolved in release `0.0.16`
