### ISSUE TITLE
This plugin generated a warning from the characteristic 'Current Temperature

### ISSUE THREAD

**Issue by domalab** [bstillitano/homebridge-actron-neo#4]
A lot of these warmings in the logs

This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 3000 exceeded maximum of 100. 

See https://homebridge.io/w/JtMGR for more info.

**Comment by bstillitano** [comment]
@ruaandeysel the noise should be signifcantly reduced now. Looks like the Que plugin had code that tried to tie all the zones together, presumably because you can have zone based temperature control. I've removed that call  for now which has brought the logging noise right down. There is still a tiny bit of noise but nowhere near as much.

**Comment by ruaandeysel** [comment]
@bstillitano Awesome! Updated it and looks good.

I can turn the zones on/off from Master Controller and then I have the zone sensors in each room to maintain precise temperature.

![Screenshot 2023-09-15 at 10 27 49 am](https://github.com/bstillitano/homebridge-actron-neo/assets/57021511/d087325a-58fc-42cc-b01a-03e39af0ce6f)

**Comment by bstillitano** [comment]
@ruaandeysel interesting, does this device actually allow zone based temperature controls or is it just a sensor? If it's just a sensor, the temps should be getting reported through the API in the same way that the normal neo controller reports it.

**Comment by ruaandeysel** [comment]
@bstillitano No individual zone based temperature control with the sensor. It connects via wired / wireless to Master Controller and looks like this 
![IMG_3964](https://github.com/bstillitano/homebridge-actron-neo/assets/57021511/1f99f85e-c415-43df-917e-b38bf759f59a)

So now I get an average internal temp / humidity from all sensors in the house.

**Comment by bstillitano** [comment]
Ahh ok cool, got it. Yeah so your temperatures should be getting reported accurately in homekit I would think. I can't see any reason that the API would report these as additional zones. Are you seeing issues with the temperature reporting?

**Comment by ruaandeysel** [comment]
To individually control each zone temp. I would have to buy these zone controllers

![Screenshot 2023-09-15 at 10 41 29 am](https://github.com/bstillitano/homebridge-actron-neo/assets/57021511/073bb852-a63f-4d60-8610-550b4c8f75b8)

**Comment by ruaandeysel** [comment]
> Ahh ok cool, got it. Yeah so your temperatures should be getting reported accurately in homekit I would think. I can't see any reason that the API would report these as additional zones. Are you seeing issues with the temperature reporting?

The zones report correct temperature 

![IMG_FE20459220A8-1](https://github.com/bstillitano/homebridge-actron-neo/assets/57021511/f23a12ba-3635-46de-bcc6-c4a076536f82)

Each zone sensor performs like a zone controller :)

![IMG_9CE31C05882F-1](https://github.com/bstillitano/homebridge-actron-neo/assets/57021511/0a4fa847-aff5-48c4-838f-4a32bd89e46e)
![IMG_0FC392902E2D-1](https://github.com/bstillitano/homebridge-actron-neo/assets/57021511/caa1bd7d-3b3b-4bae-8a3c-d57593954f8e)

**Comment by bstillitano** [comment]
Good stuff!

**Comment by ruaandeysel** [comment]
Any idea how to disable the temperature dial for the zone if you don't use zone controllers? So it just shows the temperature and toggle switch to enable or disable the zone?

**Comment by bstillitano** [comment]
@ruaandeysel that's something I was thinking too, I might add a config that lets you choose whether the zones are lightbulbs or heater/cooler accessories. It is a bit "eh" in my mind to have the temp control given I can't use it. I'll work on this over the weekend.

**Comment by ruaandeysel** [comment]
Yeah true! Zones could also just be a switch or fan...

**Comment by ruaandeysel** [comment]
> @ruaandeysel that's something I was thinking too, I might add a config that lets you choose whether the zones are lightbulbs or heater/cooler accessories. It is a bit "eh" in my mind to have the temp control given I can't use it. I'll work on this over the weekend.

I noticed the latest update added lights for zones in HomeKit.

Problem is that now HomeKit see it as additional lights in the house which is confusing the missus. :)

**Comment by bstillitano** [comment]
If you don’t want the light switches there for now please use the version
before the current one which should remove them whilst I find time to tweak
this.

**Comment by murali0286** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @redmac, @karmicDev, @RayZhao1998, @jereinste, @Ornolfr, @ohtwo, @jackcsk, @Danappelxx, @abdullahumer, @mkll, @Stoppels, @cypherkitty, @CedricEugeni, @trevorwang, @jvcol, @sk-chanch, @vakhidbetrakhmadov, @MQL9011, @bernielxy, @j4tmr

**Comment by bstillitano** [comment]
Hey @domalab 

I saw you had forked this and made some great improvements.

If you'd like to raise a PR I can merge the changes in and tag a release for the community

**Comment by domalab** [comment]
Hello @bstillitano ,

I raised a PR.

I noticed @jxg81 made some updates to his Que code and looking if any can be used with Neo.

**Comment by bstillitano** [comment]
Thanks @domalab there are a few things in that PR that need to be updated, primarily around removing the git templates and renaming the package (which breaks NPM in some cases and homebridge verification status). 

I'll leave some detailed feedback when I'm back at my desk but once these minor things are addressed we can definitely merge it in.

If you're happy for me to address the feedback also, to save you having to do it, I'm happy to do that also.

**Comment by domalab** [comment]
> Thanks @domalab there are a few things in that PR that need to be updated, primarily around removing the git templates and renaming the package (which breaks NPM in some cases and homebridge verification status).
> 
> I'll leave some detailed feedback when I'm back at my desk but once these minor things are addressed we can definitely merge it in.
> 
> If you're happy for me to address the feedback also, to save you having to do it, I'm happy to do that also.

Feedback is welcome and helping to address it will be appreciated.

**Comment by bstillitano** [comment]
> > Thanks @domalab there are a few things in that PR that need to be updated, primarily around removing the git templates and renaming the package (which breaks NPM in some cases and homebridge verification status).
> 
> > 
> 
> > I'll leave some detailed feedback when I'm back at my desk but once these minor things are addressed we can definitely merge it in.
> 
> > 
> 
> > If you're happy for me to address the feedback also, to save you having to do it, I'm happy to do that also.
> 
> 
> 
> Feedback is welcome and helping to address it will be appreciated. 

Legend. Appreciate it. I'll get onto it this arvo. Thank you

**Comment by domalab** [comment]
> A lot of these warmings in the logs
> 
> This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 3000 exceeded maximum of 100.
> 
> See https://homebridge.io/w/JtMGR for more info.

@bstillitano I resolved this warning. I noticed it's coming from the outdoorUnitAccessory which in my system the temp is locked to 3000 for some reason. Maybe the QUE system has an outdoor temp sensor or maybe there's a model of outdoor unit that has a temp sensor. Model I have don't have outdoor temp sensor that I know off.

**Comment by bstillitano** [comment]
@domalab yeah the neo has no outdoor sensor as far as I'm aware, only internal

**Comment by bstillitano** [comment]
This is resolved in version 0.0.26
