### ISSUE TITLE
Many warning messages in log: ...from the characteristic 'Cooling Threshold Temperature'...

### ISSUE THREAD

**Issue by alvlam** [bstillitano/homebridge-actron-neo#9]
Full warning message:

_[homebridge-actron-neo] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 24.5 exceeded maximum of 24. See https://homebridge.io/w/JtMGR for more info._

![image](https://github.com/bstillitano/homebridge-actron-neo/assets/43482046/abfee165-5184-4224-aa95-df1f84d99570)

I've tried changing the default max cooling temp in settings (from 24 to 23 but this had no effect).

**Comment by bstillitano** [comment]
This is resolved in version 0.0.26

**Comment by alvlam** [comment]
Hi again,Finally got around to updating to new version, thanks for the fix. But unfortunately seem to have lost the ability to show individual temp tiles in secondary zones?CheersOn 22 Jul 2024, at 11:31 PM, Brandon Stillitano ***@***.***> wrote:﻿
This is resolved in version 0.0.26

**Comment by bstillitano** [comment]
@alvlam that functionality was removed as it was flaky at best and not enough is understood about it on my end. If you're willing to spend the time creating a PR to implement it properly (or even just revert the removal) and testing it throughly, we can re-introduce it.

**Comment by alvlam** [comment]
Thanks, I will see what I can figure out. The data itself is being pulled in, from what I can tell. It’s just the type of display tile?On 19 Aug 2024, at 7:54 PM, Brandon Stillitano ***@***.***> wrote:﻿
@alvlam that functionality was removed as it was flaky at best and not enough is understood about it on my end. If you're willing to spend the time creating a PR to implement it properly (or even just revert the removal) and testing it throughly, we can re-introduce it.
